### ISSUE TITLE
October 7 is missing

### ISSUE THREAD

**Issue by liamdawson** [zmxv/everydaycalendar#2]
![screenshot_20181109_092812](https://user-images.githubusercontent.com/760143/48231348-e3a2d600-e401-11e8-8653-5f51d89d73be.png)

Tested in Firefox Developer Edition, and Chromium.

**Comment by liamdawson** [comment]
Interestingly enough, that's the day that Daylight Savings began in my timezone. (`Australia/Melbourne`)
On the other hand, the button for April 1 (when DST ended this year) is duplicated in the DOM:

![screenshot_20181109_093705](https://user-images.githubusercontent.com/760143/48231678-113c4f00-e403-11e8-8851-ffb1b2967fd5.png)

**Comment by zmxv** [comment]
Nice catch, thanks! I've patched the daylight savings bug with a quick and dirty hack.
A cleaner (albeit longer) fix would need an alternative way to enumerate days.
