### ISSUE TITLE
Information on the back of the calendar doesn't load in Firefox

### ISSUE THREAD

**Issue by liamdawson** [zmxv/everydaycalendar#3]
![screenshot_20181109_093019](https://user-images.githubusercontent.com/760143/48231419-219ffa00-e402-11e8-8c08-603adf4d7ec1.png)

Tested in Firefox Developer Edition, and latest stable Firefox, with and without an adblocker.

**Comment by zmxv** [comment]
Fixed and tested in Firefox 71.
